CREATE TABLE `invites` (
  `invite_id` INT64 NOT NULL,
  `entity_id` INT64 NOT NULL,
  `requester_id` INT64 DEFAULT NULL,
  `inviter_id` INT64 DEFAULT NULL,
  `type` STRING(150) NOT NULL,
  `recipient` STRING(150) NOT NULL,
  `referral_code` STRING(150) DEFAULT NULL,
  `status` STRING(150) NOT NULL,
  `created_by` INT64 NOT NULL,
  `updated_by` INT64 NOT NULL,
  `deleted_by` INT64 DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP DEFAULT NULL
) PRIMARY KEY (invite_id)
